# Generated by Django 3.0.8 on 2020-07-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customers', models.CharField(max_length=120)),
                ('item', models.TextField()),
                ('total', models.TextField()),
                ('quantity', models.TextField()),
                ('date', models.TextField()),
            ],
        ),
    ]
